language: go
sudo: false 

branches:
    only:
    - master
    - /v\d+\.\d+[a-z]/

notifications: # 每次构建的时候是否通知，如果不想收到通知，那就设置false吧(email: false,也可以是Slack)
  # slack: xxxx:xxxxxxxxxx
  email: osla.zy@gmail.com
  on_success: change
  on_failure: always

go:
  - 1.9.2
  # - tip

env:
  - "PATH=$HOME/gopath/bin:$PATH"

# before_install:
#   - go get 


# before_install:
#   - go get github.com/stretchr/testify/assert
#   - go get github.com/axw/gocov/gocov
#   - go get github.com/mattn/goveralls
#   - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
    - sed -i 's/367116221053-7n0vf5akeru7on6o2fjinrecpdoe99eg.apps.googleusercontent.com/262618276336-glgjqtr05dmti8f4qv6ft44p9ts8iq8c.apps.googleusercontent.com/g;s/1qsNodXNaWq1mQuBjUjmvhoO/I2JmHM4kgVj4XJDx1oL7W0t0/g' handlers_drive.go
    - go get -d -v ./...
    - sudo apt update 
    - sudo apt install upx -y

script:
  - pwd;ls -alth;whoami
  - bash _release/build-all.sh
  # - cd _release/bin; for i in `ls`;do upx $i ; done
  # - cd _release/bin; for i in `ls`;do upx $i ; done


before_deploy:
  - echo "GIT_TAG is "
  - echo $GIT_TAG
  - VERSION=$(_release/bin/gdrive-linux-x64 version | awk 'NR==1 {print $2}')
  - echo $VERSION
  - export GIT_TAG=$VERSION
  - export TAG=false
  - if [ ! -z "$TRAVIS_TAG" ] ; then
        export GIT_TAG=$TRAVIS_TAG;
        export TAG=true;
    fi

deploy:
  provider: releases
  api_key: $AUTH_TOKEN
  tag_name: $GIT_TAG$TRAVIS_COMMIT
  # $TRAVIS_TAG
  # target_commitish: $GIT_TAG
  # target_commitish: $TRAVIS_COMMIT
  # $GIT_COMMIT
  name: $GIT_TAG-$TRAVIS_COMMIT
  #$GIT_TAG
  body: Automated release from Travis CI with added files from gdrive build
  # TRAVIS_TAG
  overwrite: true
  skip_cleanup: true
  on:
    branch: master
    # tags: $GIT_TAG
  file_glob: true
  file: _release/bin/*
  # file:
  #   - "_release/bin/gdrive-dragonfly-x64"
  #   - "_release/bin/gdrive-freebsd-386"
  #   - "_release/bin/gdrive-freebsd-arm"
  #   - "_release/bin/gdrive-freebsd-x64"
  #   - "_release/bin/gdrive-linux-386"
  #   - "_release/bin/gdrive-linux-arm"
  #   - "_release/bin/gdrive-linux-arm64"
  #   - "_release/bin/gdrive-linux-mips64"
  #   - "_release/bin/gdrive-linux-mips64le"
  #   - "_release/bin/gdrive-linux-ppc64"
  #   - "_release/bin/gdrive-linux-ppc64le"
  #   - "_release/bin/gdrive-linux-rpi"
  #   - "_release/bin/gdrive-linux-x64"
  #   - "_release/bin/gdrive-netbsd-386"
  #   - "_release/bin/gdrive-netbsd-arm"
  #   - "_release/bin/gdrive-netbsd-x64"
  #   - "_release/bin/gdrive-openbsd-386"
  #   - "_release/bin/gdrive-openbsd-arm"
  #   - "_release/bin/gdrive-openbsd-x64"
  #   - "_release/bin/gdrive-osx-386"
  #   - "_release/bin/gdrive-osx-x64"
  #   - "_release/bin/gdrive-plan9-386"
  #   - "_release/bin/gdrive-plan9-x64"
  #   - "_release/bin/gdrive-solaris-x64"
  #   - "_release/bin/gdrive-windows-386.exe"
  #   - "_release/bin/gdrive-windows-x64.exe"




# script:
#   - go test -v -covermode=count -coverprofile=coverage.out
#   - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
